pub mod fetch;
pub mod scan;
pub mod validation;

use crate::modules::logger;
use crate::modules::types::AppError;
use std::time::Duration;

// Re-export all items (includes __cmd__ and __specta__fn__ generated by proc macros)
pub use fetch::*;
pub use scan::*;
pub use validation::*;

/// Map yt-dlp stderr output to a stable i18n key. The frontend translates the key into the
/// user's current UI language (see `extractError` + `src/lib/i18n/locales`). The raw stderr is
/// logged by the caller, so messages stay clean and fully localized for every language.
fn map_stderr_error(stderr: &str) -> AppError {
    // Match specific age-restriction phrases only, and BEFORE any "Sign in" handling: the real
    // YouTube age gate is "Sign in to confirm your age. This video may be inappropriate for
    // some users." A bare "age" substring also matches the very common "Unable to download
    // webpage" error, mislabeling network failures as age-restricted content.
    if stderr.contains("confirm your age")
        || stderr.contains("age-restricted")
        || stderr.contains("age restricted")
        || stderr.contains("inappropriate for some users")
    {
        return AppError::MetadataError("error.ageRestricted".to_string());
    }
    // YouTube anti-bot check: "Sign in to confirm you're not a bot. Use --cookies-from-browser
    // ...". Matching "not a bot" sidesteps the apostrophe variants (you're / you’re).
    if stderr.contains("not a bot") {
        return AppError::MetadataError("error.botCheck".to_string());
    }
    if stderr.contains("Private video") {
        return AppError::MetadataError("error.privateVideo".to_string());
    }
    // The --impersonate retry against a yt-dlp built without curl_cffi fails with
    // 'Impersonate target "chrome" is not available' — match it before the broad
    // "not available" branch below so a live video isn't reported as unavailable.
    if stderr.contains("Impersonate target") || stderr.contains("curl_cffi") {
        return AppError::MetadataError("error.impersonateUnavailable".to_string());
    }
    if stderr.contains("Video unavailable") || stderr.contains("not available") {
        return AppError::MetadataError("error.videoUnavailable".to_string());
    }
    if stderr.contains("is not a valid URL") || stderr.contains("Unsupported URL") {
        return AppError::InvalidUrl("error.unsupportedUrl".to_string());
    }
    // 429 must stay before the 403 branch: rate limiting isn't fixable with cookies.
    if stderr.contains("HTTP Error 429") || stderr.contains("Too Many Requests") {
        return AppError::NetworkError("error.tooManyRequests".to_string());
    }
    // 410/403이 여기까지 왔다는 건 --impersonate 자동 재시도(run_with_impersonate_fallback)에도
    // 여전히 차단됐다는 뜻이다.
    if stderr.contains("HTTP Error 410")
        || stderr.contains(": Gone")
        || stderr.contains("HTTP Error 403")
        || stderr.contains("Forbidden")
    {
        return AppError::MetadataError("error.siteBlocked".to_string());
    }
    if stderr.contains("No video formats found") {
        return AppError::MetadataError("error.noFormats".to_string());
    }
    // "Could not copy" = cookie DB locked by a running browser; "cookies database" = yt-dlp's
    // lowercase "could not find <browser> cookies database in ..." for an uninstalled browser
    // or an unreadable profile (e.g. Safari without Full Disk Access).
    if (stderr.contains("Could not copy") && stderr.contains("cookie"))
        || stderr.contains("cookies database")
    {
        return AppError::MetadataError("error.cookieAccess".to_string());
    }
    // Late catch-all: nearly every remaining "Sign in ..." yt-dlp error is cookie-fixable, so
    // keep the coverage the old broad "Sign in" branch had, just with an accurate label.
    if stderr.contains("Sign in") {
        return AppError::MetadataError("error.botCheck".to_string());
    }

    AppError::MetadataError("error.ytdlpGeneric".to_string())
}

/// 안티봇(주로 TLS 핑거프린팅)으로 의심되는 실패인지 판단한다. 이런 경우 yt-dlp
/// `--impersonate`로 브라우저를 위장하면 통과하는 경우가 많다(예: PornHub의 HTTP 410 Gone).
/// 403 Forbidden도 포함. 429(rate limit)는 impersonate로 풀리지 않으므로 제외한다.
pub(crate) fn looks_like_antibot_block(stderr: &str) -> bool {
    stderr.contains("HTTP Error 410")
        || stderr.contains(": Gone")
        || stderr.contains("HTTP Error 403")
        || stderr.contains("Forbidden")
}

/// `--impersonate` 재시도에 사용할 기본 타겟. yt-dlp가 사용 가능한 최신 Chrome으로 매핑한다.
pub(crate) const IMPERSONATE_TARGET: &str = "chrome";

/// yt-dlp를 실행하고, 안티봇으로 의심되는 실패(410/403)면 `--impersonate`를 붙여 1회만
/// 자동 재시도한다. 성공이거나 비-안티봇 실패면 첫 결과를 그대로 반환한다(호출부가
/// map_stderr_error로 변환). 평소에는 impersonate를 쓰지 않아 성능·호환성 영향이 없다.
/// `build_cmd(impersonate)`가 시도마다 Command를 새로 만든다. 인자가 `-- <url>`로 끝나기
/// 때문에 기존 Command에 `--impersonate`를 덧붙이면 플래그가 아니라 URL로 파싱된다.
pub(super) async fn run_with_impersonate_fallback<F>(
    build_cmd: F,
    timeout: Duration,
    timeout_msg: &str,
) -> Result<std::process::Output, AppError>
where
    F: Fn(bool) -> tokio::process::Command,
{
    let first = tokio::time::timeout(timeout, build_cmd(false).output())
        .await
        .map_err(|_| AppError::MetadataError(timeout_msg.to_string()))?
        .map_err(|e| {
            logger::error_cat("metadata", &format!("yt-dlp exec failed: {}", e));
            AppError::MetadataError("error.ytdlpExecFailed".to_string())
        })?;

    if first.status.success() || !looks_like_antibot_block(&String::from_utf8_lossy(&first.stderr))
    {
        return Ok(first);
    }

    logger::warn_cat(
        "metadata",
        "anti-bot block detected (410/403), retrying with --impersonate",
    );
    let retry = tokio::time::timeout(timeout, build_cmd(true).output())
        .await
        .map_err(|_| AppError::MetadataError(timeout_msg.to_string()))?
        .map_err(|e| {
            logger::error_cat("metadata", &format!("yt-dlp exec failed: {}", e));
            AppError::MetadataError("error.ytdlpExecFailed".to_string())
        })?;
    Ok(retry)
}

#[cfg(test)]
mod tests {
    use super::{looks_like_antibot_block, map_stderr_error};
    use crate::modules::types::AppError;

    fn key(stderr: &str) -> String {
        match map_stderr_error(stderr) {
            AppError::MetadataError(k) | AppError::InvalidUrl(k) | AppError::NetworkError(k) => k,
            other => panic!("unexpected error variant: {:?}", other),
        }
    }

    #[test]
    fn bot_check_wins_over_private_video() {
        // Real YouTube anti-bot message (the dominant failure since 2024).
        assert_eq!(
            key("ERROR: [youtube] dQw4w9WgXcQ: Sign in to confirm you're not a bot. Use --cookies-from-browser or --cookies for the authentication."),
            "error.botCheck"
        );
    }

    #[test]
    fn age_gate_wins_over_sign_in() {
        // Real YouTube age-gate message also starts with "Sign in".
        assert_eq!(
            key("ERROR: [youtube] abc: Sign in to confirm your age. This video may be inappropriate for some users."),
            "error.ageRestricted"
        );
    }

    #[test]
    fn private_video_still_matches() {
        assert_eq!(
            key("ERROR: [youtube] abc: Private video. Sign in if you've been granted access to this video"),
            "error.privateVideo"
        );
    }

    #[test]
    fn bare_sign_in_falls_back_to_bot_check() {
        assert_eq!(
            key("ERROR: [youtube] abc: Sign in to view this content"),
            "error.botCheck"
        );
    }

    #[test]
    fn impersonate_target_not_available_is_not_video_unavailable() {
        assert_eq!(
            key("ERROR: Impersonate target \"chrome\" is not available. You may be missing dependencies required to support this target."),
            "error.impersonateUnavailable"
        );
    }

    #[test]
    fn geo_block_still_maps_to_video_unavailable() {
        assert_eq!(
            key("ERROR: [youtube] abc: This video is not available in your country"),
            "error.videoUnavailable"
        );
    }

    #[test]
    fn persistent_403_maps_to_site_blocked() {
        assert_eq!(
            key("ERROR: unable to download video data: HTTP Error 403: Forbidden"),
            "error.siteBlocked"
        );
    }

    #[test]
    fn rate_limit_stays_too_many_requests() {
        assert_eq!(
            key("ERROR: HTTP Error 429: Too Many Requests"),
            "error.tooManyRequests"
        );
    }

    #[test]
    fn missing_cookies_database_maps_to_cookie_access() {
        assert_eq!(
            key("ERROR: could not find chrome cookies database in \"~/Library/Application Support/Google/Chrome\""),
            "error.cookieAccess"
        );
    }

    #[test]
    fn antibot_block_detects_410_and_403() {
        assert!(looks_like_antibot_block(
            "ERROR: [pornhub] 6a0cedc51e733: Unable to download webpage: HTTP Error 410: Gone"
        ));
        assert!(looks_like_antibot_block("HTTP Error 403: Forbidden"));
        assert!(looks_like_antibot_block("something failed: Gone"));
    }

    #[test]
    fn antibot_block_ignores_normal_errors() {
        assert!(!looks_like_antibot_block("ERROR: Video unavailable"));
        assert!(!looks_like_antibot_block(
            "HTTP Error 429: Too Many Requests"
        ));
        assert!(!looks_like_antibot_block(""));
    }
}
