pub mod fetch;
pub mod validation;

use crate::modules::logger;
use crate::modules::types::AppError;
use std::time::Duration;

// Re-export all items (includes __cmd__ and __specta__fn__ generated by proc macros)
pub use fetch::*;
pub use validation::*;

/// Map yt-dlp stderr output to a stable i18n key. The frontend translates the key into the
/// user's current UI language (see `extractError` + `src/lib/i18n/locales`). The raw stderr is
/// logged by the caller, so messages stay clean and fully localized for every language.
fn map_stderr_error(stderr: &str) -> AppError {
    if stderr.contains("Private video") || stderr.contains("Sign in") {
        return AppError::MetadataError("error.privateVideo".to_string());
    }
    if stderr.contains("Video unavailable") || stderr.contains("not available") {
        return AppError::MetadataError("error.videoUnavailable".to_string());
    }
    if stderr.contains("is not a valid URL") || stderr.contains("Unsupported URL") {
        return AppError::InvalidUrl("error.unsupportedUrl".to_string());
    }
    if stderr.contains("HTTP Error 429") || stderr.contains("Too Many Requests") {
        return AppError::NetworkError("error.tooManyRequests".to_string());
    }
    // 410이 여기까지 왔다는 건 --impersonate 자동 재시도(run_with_impersonate_fallback)에도
    // 여전히 차단됐다는 뜻이다.
    if stderr.contains("HTTP Error 410") || stderr.contains(": Gone") {
        return AppError::MetadataError("error.siteBlocked".to_string());
    }
    if stderr.contains("No video formats found") {
        return AppError::MetadataError("error.noFormats".to_string());
    }
    // Match specific age-restriction phrases only. A bare "age" substring also matches the
    // very common "Unable to download webpage" error, mislabeling network failures as
    // age-restricted content.
    if stderr.contains("confirm your age")
        || stderr.contains("age-restricted")
        || stderr.contains("age restricted")
        || stderr.contains("inappropriate for some users")
    {
        return AppError::MetadataError("error.ageRestricted".to_string());
    }
    if stderr.contains("Could not copy") && stderr.contains("cookie") {
        return AppError::MetadataError("error.cookieAccess".to_string());
    }

    AppError::MetadataError("error.ytdlpGeneric".to_string())
}

/// 안티봇(주로 TLS 핑거프린팅)으로 의심되는 실패인지 판단한다. 이런 경우 yt-dlp
/// `--impersonate`로 브라우저를 위장하면 통과하는 경우가 많다(예: PornHub의 HTTP 410 Gone).
/// 403 Forbidden도 포함. 429(rate limit)는 impersonate로 풀리지 않으므로 제외한다.
pub(crate) fn looks_like_antibot_block(stderr: &str) -> bool {
    stderr.contains("HTTP Error 410")
        || stderr.contains(": Gone")
        || stderr.contains("HTTP Error 403")
        || stderr.contains("Forbidden")
}

/// `--impersonate` 재시도에 사용할 기본 타겟. yt-dlp가 사용 가능한 최신 Chrome으로 매핑한다.
pub(crate) const IMPERSONATE_TARGET: &str = "chrome";

/// yt-dlp를 실행하고, 안티봇으로 의심되는 실패(410/403)면 `--impersonate`를 붙여 1회만
/// 자동 재시도한다. 성공이거나 비-안티봇 실패면 첫 결과를 그대로 반환한다(호출부가
/// map_stderr_error로 변환). 평소에는 impersonate를 쓰지 않아 성능·호환성 영향이 없다.
pub(super) async fn run_with_impersonate_fallback(
    mut cmd: tokio::process::Command,
    timeout: Duration,
    timeout_msg: &str,
) -> Result<std::process::Output, AppError> {
    let first = tokio::time::timeout(timeout, cmd.output())
        .await
        .map_err(|_| AppError::MetadataError(timeout_msg.to_string()))?
        .map_err(|e| {
            logger::error_cat("metadata", &format!("yt-dlp exec failed: {}", e));
            AppError::MetadataError("error.ytdlpExecFailed".to_string())
        })?;

    if first.status.success() || !looks_like_antibot_block(&String::from_utf8_lossy(&first.stderr))
    {
        return Ok(first);
    }

    logger::warn_cat(
        "metadata",
        "anti-bot block detected (410/403), retrying with --impersonate",
    );
    cmd.arg("--impersonate").arg(IMPERSONATE_TARGET);
    let retry = tokio::time::timeout(timeout, cmd.output())
        .await
        .map_err(|_| AppError::MetadataError(timeout_msg.to_string()))?
        .map_err(|e| {
            logger::error_cat("metadata", &format!("yt-dlp exec failed: {}", e));
            AppError::MetadataError("error.ytdlpExecFailed".to_string())
        })?;
    Ok(retry)
}

#[cfg(test)]
mod tests {
    use super::looks_like_antibot_block;

    #[test]
    fn antibot_block_detects_410_and_403() {
        assert!(looks_like_antibot_block(
            "ERROR: [pornhub] 6a0cedc51e733: Unable to download webpage: HTTP Error 410: Gone"
        ));
        assert!(looks_like_antibot_block("HTTP Error 403: Forbidden"));
        assert!(looks_like_antibot_block("something failed: Gone"));
    }

    #[test]
    fn antibot_block_ignores_normal_errors() {
        assert!(!looks_like_antibot_block("ERROR: Video unavailable"));
        assert!(!looks_like_antibot_block(
            "HTTP Error 429: Too Many Requests"
        ));
        assert!(!looks_like_antibot_block(""));
    }
}
