//! Streaming playlist/channel scan.
//!
//! 채널/플레이리스트 분석은 단일 yt-dlp 프로세스(`--flat-playlist --lazy-playlist --dump-json`)
//! 하나로 끝까지 스트리밍한다. 예전 `-I start:end` 페이지 방식은 yt-dlp가 YouTube continuation을
//! 순차적으로만 따라갈 수 있어 페이지 k마다 앞의 항목 전부를 다시 걸어갔다(총 O(n²) 요청).
//! 여기서는 stdout NDJSON을 줄 단위로 읽어 배치 단위 `PlaylistScanEvent`로 프런트에 보낸다.

use super::fetch::{extract_scan_meta, normalize_bare_channel_url, parse_flat_entry};
use super::{looks_like_antibot_block, map_stderr_error, IMPERSONATE_TARGET};
use crate::modules::logger;
use crate::modules::types::AppError;
use crate::ytdlp::download::{append_limited, kill_process_tree};
use crate::ytdlp::types::*;
use crate::ytdlp::{binary, security};
use std::process::Stdio;
use std::sync::{Arc, Mutex};
use std::time::Duration;
use tauri::{AppHandle, Emitter, Manager};
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::sync::{mpsc, watch};

/// Flush a batch to the frontend once it reaches this many entries…
const SCAN_BATCH_SIZE: usize = 30;
/// …or this long after the first buffered entry, whichever comes first.
const SCAN_FLUSH_INTERVAL: Duration = Duration::from_millis(300);
/// yt-dlp가 이 시간 동안 한 줄도 출력하지 않으면 멈춘 것으로 보고 종료한다. 총량 제한이
/// 아니라 무활동 제한이라 1만 개 채널도 계속 출력만 하면 제한 없이 끝까지 스캔된다.
const SCAN_INACTIVITY_TIMEOUT: Duration = Duration::from_secs(90);
/// Absolute safety cap for a single scan.
const SCAN_HARD_TIMEOUT: Duration = Duration::from_secs(2 * 60 * 60);
const SCAN_STDERR_LIMIT_BYTES: usize = 64 * 1024;

/// Tracks the single active scan. Starting a new scan cancels the previous one, so at most
/// one yt-dlp listing process runs at a time (mirrors DownloadManager's watch::channel pattern).
#[derive(Default)]
pub struct ScanManager {
    current: Mutex<Option<(u32, watch::Sender<bool>)>>,
}

impl ScanManager {
    /// Register `scan_id` as the active scan, cancelling any previous one.
    pub fn begin(&self, scan_id: u32) -> watch::Receiver<bool> {
        let (tx, rx) = watch::channel(false);
        let mut current = self.current.lock().unwrap_or_else(|e| e.into_inner());
        if let Some((_, old_tx)) = current.replace((scan_id, tx)) {
            let _ = old_tx.send(true);
        }
        rx
    }

    /// Cancel `scan_id` if it is still the active scan (stale ids are ignored).
    pub fn cancel(&self, scan_id: u32) {
        let mut current = self.current.lock().unwrap_or_else(|e| e.into_inner());
        if matches!(*current, Some((id, _)) if id == scan_id) {
            if let Some((_, tx)) = current.take() {
                let _ = tx.send(true);
            }
        }
    }

    /// 앱 종료 시 활성 스캔 취소 (yt-dlp 고아 프로세스 방지).
    pub fn cancel_current(&self) {
        let mut current = self.current.lock().unwrap_or_else(|e| e.into_inner());
        if let Some((_, tx)) = current.take() {
            let _ = tx.send(true);
        }
    }

    /// Clear the slot when a scan ends on its own (no-op if it was already replaced).
    fn finish(&self, scan_id: u32) {
        let mut current = self.current.lock().unwrap_or_else(|e| e.into_inner());
        if matches!(*current, Some((id, _)) if id == scan_id) {
            *current = None;
        }
    }
}

/// Start a streaming playlist/channel scan. Returns immediately; entries and the terminal
/// state arrive via `PlaylistScanEvent` ("playlist-scan-event"). `scan_id` is generated by
/// the frontend so its event handler can already filter on it before this command resolves.
#[tauri::command]
#[specta::specta]
pub async fn start_playlist_scan(
    app: AppHandle,
    url: String,
    scan_id: u32,
) -> Result<(), AppError> {
    let url = security::sanitize_url(&url)?;
    // 탭 없는 채널 URL은 Videos/Shorts 탭이 별도 플레이리스트로 잡혀 항목이 섞이고 웹페이지를
    // 더 받는다. /videos 탭으로 고정한다.
    let url = normalize_bare_channel_url(&url);
    logger::info_cat(
        "metadata",
        &format!("Starting playlist scan {}: {}", scan_id, url),
    );
    // Resolve the binary up-front so a missing yt-dlp fails the command itself
    // instead of surfacing only as an async "error" event.
    let ytdlp_path = binary::resolve_ytdlp_path_with_app(&app).await?;
    let manager = app.state::<crate::ScanManagerState>().inner().clone();
    let cancel_rx = manager.begin(scan_id);
    tauri::async_runtime::spawn(run_scan(
        app.clone(),
        manager,
        scan_id,
        url,
        ytdlp_path,
        cancel_rx,
    ));
    Ok(())
}

#[tauri::command]
#[specta::specta]
pub async fn cancel_playlist_scan(app: AppHandle, scan_id: u32) -> Result<(), AppError> {
    logger::info_cat("metadata", &format!("Cancelling playlist scan {}", scan_id));
    app.state::<crate::ScanManagerState>().cancel(scan_id);
    Ok(())
}

enum ScanOutcome {
    Done {
        total: u32,
    },
    Error {
        key: String,
        total: u32,
    },
    Cancelled,
    /// exit != 0 with zero entries delivered and stderr that looks like an anti-bot block —
    /// safe to retry from scratch with `--impersonate` (no duplicates possible).
    AntibotBlocked,
}

async fn run_scan(
    app: AppHandle,
    manager: Arc<ScanManager>,
    scan_id: u32,
    url: String,
    ytdlp_path: String,
    mut cancel_rx: watch::Receiver<bool>,
) {
    let mut outcome =
        run_scan_attempt(&app, scan_id, &url, &ytdlp_path, false, &mut cancel_rx).await;
    if matches!(outcome, ScanOutcome::AntibotBlocked) {
        logger::warn_cat(
            "metadata",
            "scan: anti-bot block detected (410/403), retrying with --impersonate",
        );
        outcome = run_scan_attempt(&app, scan_id, &url, &ytdlp_path, true, &mut cancel_rx).await;
    }
    manager.finish(scan_id);

    let (event_type, total, message) = match outcome {
        ScanOutcome::Done { total } => {
            logger::info_cat(
                "metadata",
                &format!("scan {} done: {} entries", scan_id, total),
            );
            ("done", total, None)
        }
        ScanOutcome::Error { key, total } => ("error", total, Some(key)),
        ScanOutcome::Cancelled => ("cancelled", 0, None),
        // Unreachable: the retry attempt runs with impersonate=true and never returns this.
        ScanOutcome::AntibotBlocked => ("error", 0, Some("error.siteBlocked".to_string())),
    };
    emit_scan(
        &app,
        PlaylistScanEvent {
            scan_id,
            event_type: event_type.to_string(),
            meta: None,
            entries: vec![],
            total,
            message,
        },
    );
}

async fn run_scan_attempt(
    app: &AppHandle,
    scan_id: u32,
    url: &str,
    ytdlp_path: &str,
    impersonate: bool,
    cancel_rx: &mut watch::Receiver<bool>,
) -> ScanOutcome {
    let settings = crate::ytdlp::settings::get_settings(app).unwrap_or_default();

    let mut cmd = binary::command_with_path_app(ytdlp_path, app);
    // --lazy-playlist makes yt-dlp print each entry as soon as its continuation page arrives
    // (extractors without lazy support fall back to one burst at the end — still one process).
    cmd.arg("--flat-playlist")
        .arg("--lazy-playlist")
        .arg("--dump-json");
    cmd.arg("--encoding").arg("UTF-8");
    if let Some(browser) = &settings.cookie_browser {
        if security::sanitize_cookie_browser(browser).is_ok() {
            cmd.arg("--cookies-from-browser").arg(browser);
        }
    }
    if impersonate {
        cmd.arg("--impersonate").arg(IMPERSONATE_TARGET);
    }
    // `--` ends option parsing so a URL beginning with `-` can never be read as a flag.
    cmd.arg("--").arg(url);
    cmd.stdin(Stdio::null());
    cmd.stdout(Stdio::piped());
    cmd.stderr(Stdio::piped());

    #[cfg(target_os = "windows")]
    {
        cmd.creation_flags(0x08000000); // CREATE_NO_WINDOW
    }
    #[cfg(unix)]
    {
        cmd.process_group(0);
    }

    let mut child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) => {
            logger::error_cat(
                "metadata",
                &format!("scan {}: failed to spawn yt-dlp: {}", scan_id, e),
            );
            return ScanOutcome::Error {
                key: "error.ytdlpExecFailed".to_string(),
                total: 0,
            };
        }
    };

    let (Some(stdout), Some(stderr)) = (child.stdout.take(), child.stderr.take()) else {
        kill_process_tree(&mut child).await;
        return ScanOutcome::Error {
            key: "error.ytdlpExecFailed".to_string(),
            total: 0,
        };
    };

    // stdout 파서 태스크: NDJSON 한 줄 → serde_json::Value. 메인 루프는 채널 recv만 select
    // 하므로(취소-안전) read_until을 select 안에서 중간에 끊어 부분 라인을 잃을 일이 없다.
    let (line_tx, mut line_rx) = mpsc::channel::<serde_json::Value>(256);
    let reader_task = tokio::spawn(async move {
        let mut reader = BufReader::new(stdout);
        let mut buf = Vec::new();
        loop {
            buf.clear();
            match reader.read_until(b'\n', &mut buf).await {
                Ok(0) => break,
                Ok(_) => {
                    let line = String::from_utf8_lossy(&buf);
                    let line = line.trim();
                    if line.is_empty() {
                        continue;
                    }
                    match serde_json::from_str::<serde_json::Value>(line) {
                        Ok(json) => {
                            if line_tx.send(json).await.is_err() {
                                break; // receiver gone (scan ended) — stop reading
                            }
                        }
                        Err(e) => logger::warn_cat(
                            "metadata",
                            &format!("Failed to parse playlist entry JSON: {}", e),
                        ),
                    }
                }
                Err(_) => continue, // non-fatal read error, keep going
            }
        }
    });

    let stderr_task = tokio::spawn(async move {
        let mut reader = BufReader::new(stderr);
        let mut buf = Vec::new();
        let mut output = String::new();
        loop {
            buf.clear();
            match reader.read_until(b'\n', &mut buf).await {
                Ok(0) => break,
                Ok(_) => {
                    let line = String::from_utf8_lossy(&buf).trim_end().to_string();
                    append_limited(&mut output, &line, SCAN_STDERR_LIMIT_BYTES);
                }
                Err(_) => continue,
            }
        }
        output
    });

    let mut batch: Vec<PlaylistEntry> = Vec::new();
    let mut meta: Option<PlaylistScanMeta> = None;
    let mut meta_extracted = false;
    let mut total: u32 = 0;
    let mut batch_deadline: Option<tokio::time::Instant> = None;
    let hard_deadline = tokio::time::Instant::now() + SCAN_HARD_TIMEOUT;

    loop {
        let flush_at = batch_deadline;
        tokio::select! {
            recv = tokio::time::timeout(SCAN_INACTIVITY_TIMEOUT, line_rx.recv()) => {
                match recv {
                    Ok(Some(json)) => {
                        if !meta_extracted {
                            meta = Some(extract_scan_meta(&json, url));
                            meta_extracted = true;
                        }
                        if let Some(entry) = parse_flat_entry(&json) {
                            batch.push(entry);
                            if batch.len() >= SCAN_BATCH_SIZE {
                                flush_entries(app, scan_id, &mut batch, &mut meta, &mut total);
                                batch_deadline = None;
                            } else if batch_deadline.is_none() {
                                batch_deadline =
                                    Some(tokio::time::Instant::now() + SCAN_FLUSH_INTERVAL);
                            }
                        }
                    }
                    Ok(None) => break, // stdout EOF
                    Err(_) => {
                        logger::error_cat(
                            "metadata",
                            &format!(
                                "scan {}: no output for {:?}, killing yt-dlp",
                                scan_id, SCAN_INACTIVITY_TIMEOUT
                            ),
                        );
                        kill_process_tree(&mut child).await;
                        // 이미 도착한 항목은 전달해 부분 목록이라도 쓸 수 있게 한다.
                        flush_entries(app, scan_id, &mut batch, &mut meta, &mut total);
                        return ScanOutcome::Error {
                            key: "error.fetchTimeout".to_string(),
                            total,
                        };
                    }
                }
            }
            // async 블록이라 unwrap은 폴링될 때만 실행된다(가드 false면 폴링 안 함).
            _ = async { tokio::time::sleep_until(flush_at.unwrap()).await }, if flush_at.is_some() => {
                flush_entries(app, scan_id, &mut batch, &mut meta, &mut total);
                batch_deadline = None;
            }
            _ = tokio::time::sleep_until(hard_deadline) => {
                logger::error_cat(
                    "metadata",
                    &format!("scan {}: hard timeout after {:?}", scan_id, SCAN_HARD_TIMEOUT),
                );
                kill_process_tree(&mut child).await;
                flush_entries(app, scan_id, &mut batch, &mut meta, &mut total);
                return ScanOutcome::Error {
                    key: "error.fetchTimeout".to_string(),
                    total,
                };
            }
            _ = cancel_rx.changed() => {
                logger::info_cat("metadata", &format!("scan {}: cancelled", scan_id));
                kill_process_tree(&mut child).await;
                return ScanOutcome::Cancelled;
            }
        }
    }

    // stdout closed: collect exit status and stderr, then deliver any tail batch.
    let _ = reader_task.await;
    let status = tokio::time::timeout(Duration::from_secs(10), child.wait()).await;
    let stderr_output = match tokio::time::timeout(Duration::from_secs(5), stderr_task).await {
        Ok(Ok(s)) => s,
        _ => String::new(),
    };
    flush_entries(app, scan_id, &mut batch, &mut meta, &mut total);

    if matches!(&status, Ok(Ok(s)) if s.success()) {
        if total == 0 {
            return ScanOutcome::Error {
                key: "error.noEntries".to_string(),
                total: 0,
            };
        }
        return ScanOutcome::Done { total };
    }

    // 부분 출력 후 재시도하면 항목이 중복되므로, 안티봇 재시도는 항목 0개일 때만 허용한다.
    if total == 0 && !impersonate && looks_like_antibot_block(&stderr_output) {
        return ScanOutcome::AntibotBlocked;
    }

    logger::error_cat(
        "metadata",
        &format!(
            "scan {} failed: {}",
            scan_id,
            security::sanitize_error_message(&stderr_output)
        ),
    );
    ScanOutcome::Error {
        key: error_key(&map_stderr_error(&stderr_output)),
        total,
    }
}

/// Emit buffered entries as one "entries" event. The first flush of a scan carries the
/// playlist meta (`meta.take()` leaves `None` for every later flush).
fn flush_entries(
    app: &AppHandle,
    scan_id: u32,
    batch: &mut Vec<PlaylistEntry>,
    meta: &mut Option<PlaylistScanMeta>,
    total: &mut u32,
) {
    if batch.is_empty() {
        return;
    }
    *total += batch.len() as u32;
    emit_scan(
        app,
        PlaylistScanEvent {
            scan_id,
            event_type: "entries".to_string(),
            meta: meta.take(),
            entries: std::mem::take(batch),
            total: *total,
            message: None,
        },
    );
}

fn emit_scan(app: &AppHandle, event: PlaylistScanEvent) {
    let _ = app.emit("playlist-scan-event", event);
}

/// Pull the i18n key out of an AppError so it can ride in the event's `message` field
/// (the frontend translates it exactly like a command-returned AppError).
fn error_key(err: &AppError) -> String {
    match err {
        AppError::FileError(s)
        | AppError::Custom(s)
        | AppError::BinaryNotFound(s)
        | AppError::DownloadError(s)
        | AppError::MetadataError(s)
        | AppError::DatabaseError(s)
        | AppError::NetworkError(s)
        | AppError::InvalidUrl(s)
        | AppError::DependencyInstallError(s)
        | AppError::ChecksumError(s)
        | AppError::NotImplemented(s) => s.clone(),
    }
}
